### ISSUE TITLE
Insert option for bam2length

### ISSUE THREAD

**Issue by rpshep** [cancerit/telomerecat#3]
Insert option requires a csv file containing 2 number. Could these be input parameters?

**Comment by byb121** [comment]
I think the insert CSV file needs an extra column to say which sample/BAM the stats are for.

The file needs to be checked before starting to process BAM files, to make sure that if given BAM has a corresponding row, otherwise calculate stats on the fly. Currently, it'll just stop working if the number of input BAMs is more than the number of rows in the file. Not sure what'll happen if BAM files are fewer.

**Comment by keiranmraine** [comment]
What stats are these, read-lengths?

**Comment by byb121** [comment]
mean insert size and sd of it.

**Comment by keiranmraine** [comment]
Requires file as matched to each input
