### ISSUE TITLE
Would telomerecat work with single cell DNA sequencing data?

### ISSUE THREAD

**Issue by rodrigoduarte88** [cancerit/telomerecat#39]
I am trying to identify a tool for analysing single cell sequencing data, but I am not sure I found one yet.

**Comment by AndyMenzies** [comment]
There is no specific reason why it shouldn't work.  telomerecat just needs a paired end bam file.  However, single cell sequencing data is notoriously messy and suffers with a lot of inconsistent coverage due to library capture issues.  I've seen some whole genome single cell sequencing look a lot like targeted data, and its not predictable targeted sequencing either, coverage is random for each sample.

So, in theory it should work, but the reliability will vary from sample to sample.  And there will be some samples it just won't like.

**Comment by rodrigoduarte88** [comment]
Thank you!! Will be giving it a try soon!! When I have some preliminary results I'll get in touch to let others know
